services:
  ner-linking-api:
    container_name: ner-linking-api
    build: .
    user: root
    environment:
      CUDA_VISIBLE_DEVICES: ""
      LANGUAGE: es
    ports:
      - "5000:5000"
    volumes:
      - .:/app    # with this, it makes no sense to use COPY ./app
      # - ./app/resources   # in prod, we want the volume to just map resources
    restart: unless-stopped
    privileged: true

networks:
  default:
    name: cogstack-net
    external: true
